# Generated by Django 3.2.4 on 2021-07-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prepeat',
        ),
    ]
